### ISSUE TITLE
Add it in rubygems

### ISSUE THREAD

**Issue by oblique** [EugenMayer/docker_registry_cli#1]
Hi,

It would be awesome if you add it in rubygems.org, so we can install it with:

```
gem install docker_registry_cli
```

**Comment by EugenMayer** [comment]
Why not :)

**Comment by EugenMayer** [comment]
Thats done for @oblique https://rubygems.org/gems/docker_registry_cli

**Comment by EugenMayer** [comment]
Be aware, i added the exectuable to a gem install docker_registry_cli should be all you need, by the executable is name

```
docker_registry_cli
```

not docker_registry

**Comment by oblique** [comment]
Thanks!
BTW, `gem install docker_registry_cli` didn't install `colorize` and `httparty` as dependencies. I had to do it explicitly. Maybe you need to define its dependencies somewhere?

**Comment by EugenMayer** [comment]
thanks for the hint, fixed the dependencies with 0.0.3
