### ISSUE TITLE
/usr/bin/env: ruby: No such file or directory

### ISSUE THREAD

**Issue by cromat** [EugenMayer/docker_registry_cli#2]
When I run docker_registry_cli list it gives me "/usr/bin/env: ruby: No such file or directory" although the env file is there.

**Comment by EugenMayer** [comment]
did you install it using the gem-way?

**Comment by cromat** [comment]
Ok. I installed ruby-full and installed cli with gem command. Now I have another problem. I am running my private registry with self signed certificate and I am getting this :

```
+root@pve:/docker_registry_cli# docker_registry_cli list
"Using existing token from config.json "
/usr/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
    from /usr/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
    from /usr/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
    from /usr/lib/ruby/2.1.0/net/http.rb:920:in `connect'
    from /usr/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
    from /usr/lib/ruby/2.1.0/net/http.rb:852:in `start'
    from /usr/lib/ruby/2.1.0/net/http.rb:1369:in `request'
    from /var/lib/gems/2.1.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
    from /var/lib/gems/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
    from /var/lib/gems/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
    from /var/lib/gems/2.1.0/gems/docker_registry_cli-0.0.3/requests/DockerRegistryRequest.rb:63:in `send_get_request'
    from /var/lib/gems/2.1.0/gems/docker_registry_cli-0.0.3/commands/DockerRegistryCommand.rb:8:in `list'
    from /var/lib/gems/2.1.0/gems/docker_registry_cli-0.0.3/bin/docker_registry_cli:116:in `<top (required)>'
    from /usr/local/bin/docker_registry_cli:23:in `load'
    from /usr/local/bin/docker_registry_cli:23:in `<main>'
```

**Comment by EugenMayer** [comment]
Are you using linux? Please install your self signed certificates ( root ) properly

**Comment by cromat** [comment]
Yes, I am using Debian 8.2 and I have installed self signed certificate again properly. When I use docker API everything works fine.

I can disable SSL check with this:

`OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE`

but it is not a solution.

**Comment by EugenMayer** [comment]
Read your linux documentation how to handle ca-certificates (properly handle self signed certificates). This has nothing to do with ruby / docker_registry_cli. 

dIsabling SSL certification validation is no option, of course.
