### ISSUE TITLE
Does delete_image free the storage?

### ISSUE THREAD

**Issue by StanleyShen** [EugenMayer/docker_registry_cli#3]
I tried to run "delete_image" but I didn't see storage being freed in docker registry VM.

I have enabled delete-> true in docker registry configuration file.

**Comment by EugenMayer** [comment]
Please see the documentation of the docker registry ( distribution ) in regard of the garbage collector https://docs.docker.com/registry/garbage-collection/ - this is nothing docker_registry_cli actually can manage / trigger AFAIK, its something you have to trigger on the server using the CLI
