### ISSUE TITLE
Could not finish request, status 404 when deleting an image

### ISSUE THREAD

**Issue by schmunk42** [EugenMayer/docker_registry_cli#6]
Image `buildref06d28739a087e7d3eef4dbe5f77a05dc0f041b62-php` is shown in list.

> Note: A tag was manually deleted from the repo/image.

```
docker_registry_cli delete_image buildref06d28739a087e7d3eef4dbe5f77a05dc0f041b62-php
```

Trying to delete the image gives an error...

```
docker_registry_cli delete_image buildref06d28739a087e7d3eef4dbe5f77a05dc0f041b62-php latest
/Library/Ruby/Gems/2.0.0/gems/docker_registry_cli-0.1.0/requests/DockerRegistryRequest.rb:83:in `throw': uncaught throw "Could not finish request, status 404" (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/docker_registry_cli-0.1.0/requests/DockerRegistryRequest.rb:83:in `send_get_request'
	from /Library/Ruby/Gems/2.0.0/gems/docker_registry_cli-0.1.0/commands/DockerRegistryCommand.rb:73:in `tags'
	from /Library/Ruby/Gems/2.0.0/gems/docker_registry_cli-0.1.0/commands/DockerRegistryCommand.rb:28:in `delete_image'
	from /Library/Ruby/Gems/2.0.0/gems/docker_registry_cli-0.1.0/bin/docker_registry_cli:100:in `<top (required)>'
	from /usr/local/bin/docker_registry_cli:23:in `load'
	from /usr/local/bin/docker_registry_cli:23:in `<main>
```

Trying to list tags for the image shows also a 404.

**Comment by EugenMayer** [comment]
is you _image name_ really called buildref06d28739a087e7d3eef4dbe5f77a05dc0f041b62-php ? it seems you do neither use image names nor tag names, but rather their sha sums?

**Comment by schmunk42** [comment]
Yes, I had that for testing or better it was accidentally built and pushed in the CI and I wanted to remove it.

I read in another issue, that this is the default behavior of the registry, like once a namespace is taken, there's no way to remove it completely. You just can remove all tags from it. Would you confirm that?

**Comment by EugenMayer** [comment]
inactivity, closed
