### ISSUE TITLE
What are the dependencies?

### ISSUE THREAD

**Issue by docbill** [EugenMayer/docker_registry_cli#7]
My best guesses:

$ sudo dnf install ruby-devel
$ sudo dnf install libffi-devel
$ gem install docker_registry_cli

But this still fails...

$ docker_registry_cli list
/home/remote/briemers/.gem/ruby/gems/ffi-1.9.17/lib/ffi/library.rb:147:in `block in ffi_lib': CoreFoundation.framework/: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation: cannot open shared object file: No such file or directory (LoadError)

It looks like corefoundation is a MacOS-X thing...

**Comment by EugenMayer** [comment]
docker_registry_cli is yet build/tested on osx only - i do at least not intend to change that, feel free to  go for that.

One particular platform-specific topic would be the keychain access, since that is were we get the credentials for the registry in case they are (hopefully)  not written plain into .docker./config.json

**Comment by docbill** [comment]
You might want to add that information to the README.md and save people a lot of time trying to get this working...

**Comment by EugenMayer** [comment]
You might have just looked into the issues for a second, finding exactly the same explanation.

**Comment by docbill** [comment]
It is easy to under estimate time wasted...   Well not really wasted, just
not applied the way I would like.


Step 1. Google for ways to delete remote repository.

Step 2. Find your comment with mentioning your tool, after a comment about
json I did not quite understand...

Step 3. Open git hub, and see the nice repo.  Read the README carefully, to
see if this is what I want.   Time spent 3 minutes.

Step 4. Look at the source for the command to see if it does anything
unexpected.   Time spent 10 minutes.

Step 5. Look do a git clone.   Time spent 30 seconds.

Step 6. Read the install instructions again.   Time spent 1 minutes.

Step 7. Run install.  Time spent 1 minute.

Step 8. Examine errors...   Deterimine I need to install ruby.   Time spent
2 minutes.

Step 10. Install Ruby.   Time spent 2 minutes.

Step 11. Run install.  Time spent 1 minute.

Step 12. Examine errors...  Google for solution.  No luck.  Guess I need
install ffi.   Time spent 15 minutes.

Step 13. Search for ffi package... and install the development package.
Time spent 5 minutes.

Step 14.  Run install.  Time spent 1 minute.

Step 15. Search again for a solution...   Time spent 10 minutes.

Step 16. Scan through the open issue subject to see if there is anything
relevant.   None of the subjects look relevant.  30 seconds

Step 17. Read the ubuntu one.  Seems to be mentioning packages that should
be installed.   Looks like that is what I got.  So it should be working, so
try again.  Time spent 3 minutes.

Step 18. Search again.  Find an open source project that seems to provide
equivalent functionality.  Examine to see if that can be dropped in.   Time
spent 10 minutes.

Step 19. Concede defeat after almost an hour trying to get this to work.
Post a message asking about dependancies.

Step 20. Start scanning some of the other open issues that didn't seem
relevant at first.   That one you state in is OS-X, and there is a question
if the module can be excluded.   Try that.   10 minutes.

Step 21. Issue is closed stating stating OS-X only.   Remove git repo.
Uninstall dependancies.   5 minutes.

Step 22. Run the original curl command in the same forum with the comment
about your repo.  But now I have realized the comment about json is a
setting that the repo administrator needs to enable.   Get an error
indicating such, and realize it was a complete waste of time.

I'm mildly pissed at wasting so much time trying to get this work.   But I
really do appreciate people like you posting an sharing there work for
FREE.   Just PLEASE PLEASE PLEASE, include basic information in your
README.txt, such as if it is known to only work on one platform and what
the dependencies are.   It saves everyone a huge amount of time, and costs
you nothing.

Thanks for your time,

Bill

**Comment by EugenMayer** [comment]
Your comment is TLTR - as you are stating, this is free of charge and no warranty.

You decided that this project needs an update, why you do not stop wasting your time writing all this, but rather do what we all do here, code is gold:  https://github.com/EugenMayer/docker_registry_cli/pull/8

I obviously do not intend to fool anybody, the older versions will also work in linux, but i do not test with it - and i neither tell you anything about compatibility in the README. That was your part you "somehow" though of. 

Gems are by no means cross platform by default.

**Comment by docbill** [comment]
I've thought about doing exactly that.   But I have to balance what is a
most productive use.  I was planning to come back later and see if I could
get this working and contribute an update.   Overall though, your
reluctance to even write the briefest of comments to save potential users
hours of false tries, indicates I would probably be better off to write my
own tools.   Really for my needs I just need a few bash scripts that will
send curl commands, nothing as sophisticated as you have here.   Still it
seems like you have some very interesting ideas in your designs, so I may
yet benefit from examining your work more carefully.

Regards,

Bill

**Comment by EugenMayer** [comment]
Wont be to easy implementing Bearer Auth JWT with a simple script, but if it does, thats a good pick then :)

**Comment by docbill** [comment]
Thanks for the recommendation.  I tend to dockerize all my tools, so I can
run them anywhere.   So any necessary secure information would probably
just be stored in /etc/secure-volume .   How the data gets there is not
something the tools need to worry about.

Regards,

Bill
